--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/jacob/.config/wpg/wallpapers/tron.png"

-- Special
background="#0b0e10"
foreground="#c8ffff"
cursor="#c8ffff"

-- Colors
color0="#0b0e10"
color1="#34D7E8"
color2="#2B99A9"
color3="#46C7D6"
color4="#278B96"
color5="#3AB5C3"
color6="#2CF1FD"
color7="#99e0e9"
color8="#95a7b6"
color9="#31ffff"
color10="#2ad1e9"
color11="#48ffff"
color12="#26becf"
color13="#3af8ff"
color14="#25ffff"
color15="#c8ffff"
