#!/usr/bin/env python3

import sys
import subprocess

try:
    external = subprocess.check_output(['geo','-g']).decode("utf-8").split('\n')
    sys.stdout.write( external[5] )
except:
    sys.stdout.write( 'connecting ...')
