#!/usr/bin/env python3

import sys
import subprocess

try:
    external = subprocess.check_output(['curl','-s', 'https://ipinfo.io/ip']).decode("utf-8").strip("\n")
    print( external )
except:
    print( "Connecting..." )
